Update: dart format for indent

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -39,8 +39,13 @@ jobs:
       - name: Get dependencies
         run: flutter pub get
 
-      - name: Flutter analyze and dart format
-        run: flutter analyze && dart format --set-exit-if-changed .
+      - name: Dart format
+        run: |
+        if dart format --set-exit-if-changed .; then
+        echo "Indentation check passed."
+        else
+        echo "Indentation check failed. Please run 'dart format' to fix code formatting issues."
+        exit 1
 
       # Runs a set of commands using the runners shell
       - name: Check flutter version
